syntax = "proto3";
package instructor;
import "Protos/base.proto";
import "google/protobuf/timestamp.proto";
import "Protos/session.proto";
option csharp_namespace = "TEM.Proto";

service InstructorService {
  rpc GetInstructor (GetInstructorRequest) returns (GetInstructorResponse);              //Get the instructor
  rpc GetSessionsWithinDate (GetSessionsWithinDateRequest) returns (GetSessionsWithinDateResponse);  //Get sessions within a specified date range for all clients belonging to this instructor 
}

message Instructor {
  base.BaseProto common = 1;
  string firstname = 2[deprecated=true]; 
  string lastname = 3[deprecated=true];
  google.protobuf.Timestamp date_of_birth = 4 [deprecated=true];
  bool is_male = 5 [deprecated=true];                // Male = true, female = false
  string email_address = 6;          // Email address
  string display_name = 7;         // Instructor name/alias
}

message GetInstructorRequest {
}

message GetInstructorResponse {
  Instructor instructor = 1; 
}

message GetSessionsWithinDateRequest {
  google.protobuf.Timestamp DateFrom = 2;
  google.protobuf.Timestamp DateTo = 3;
}

message GetSessionsWithinDateResponse {
  repeated session.Session sessions = 1;
}